apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.pilot.neo9.fr
spec:
  group: pilot.neo9.fr
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            healthCheck:
              properties:
                path:
                  type: string
              type: object
            initTag:
              type: string
            pod:
              properties:
                secrets:
                  items:
                    properties:
                      key:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    - key
                    type: object
                  anyOf:
                    - type: null
                    - type: array
              type: object
            replicas:
              format: int32
              type: integer
            repository:
              type: string
            resources:
              properties:
                cpu:
                  type: string
                memory:
                  type: string
              type: object
            service:
              properties:
                port:
                  format: int32
                  type: integer
                targetPort:
                  format: int32
                  type: integer
              type: object
            tag:
              type: string
            type:
              type: string
          required:
          - type
          - repository
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
