apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pilot-operator
  template:
    metadata:
      labels:
        name: pilot-operator
    spec:
      serviceAccountName: pilot-operator
      containers:
        - name: pilot-operator
          # Do not use latest and check for latest release tag
          image: neo9sas/pilot-operator:latest
          command:
          - pilot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pilot-operator"
