apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-operator
  namespace: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pilot-operator
  template:
    metadata:
      labels:
        name: pilot-operator
    spec:
      serviceAccountName: pilot-operator
      containers:
        - name: pilot-operator
          # Replace this with the built image name
          image: 423202242239.dkr.ecr.eu-west-1.amazonaws.com/pilot-operator:latest
          command:
          - pilot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pilot-operator"
